<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_User Group_radio-control</name>
   <tag></tag>
   <elementGuidId>e50731df-0db9-4ca5-93c5-b485076847f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[3]/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;nu-theme-cloud-app-light nu-light-theme nu-nav-style-collapsible nu-responsive-medium nu-responsive-medium-only&quot;]/ftnt-app[1]/ftnt-shell[@class=&quot;ng-star-inserted&quot;]/nu-router-outlet[@class=&quot;ng-tns-c81-0 ng-trigger ng-trigger-routeAnimation ng-star-inserted&quot;]/ftnt-user-create[@class=&quot;ng-star-inserted&quot;]/nu-dialog[1]/main[1]/form[@class=&quot;ng-valid ng-touched ng-dirty&quot;]/section[1]/nu-radio-card-group[@class=&quot;ng-valid ng-touched ng-dirty&quot;]/label[@class=&quot;radio ng-star-inserted&quot;]/span[@class=&quot;radio-input&quot;]/span[@class=&quot;radio-control&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/span/span</value>
   </webElementXpaths>
</WebElementEntity>
